//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGymEntities : DbContext
    {
        public DBGymEntities()
            : base("name=DBGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblKomod> tblKomods { get; set; }
        public virtual DbSet<tblTarakonesh> tblTarakoneshes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
