//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarakonesh
    {
        public int ID { get; set; }
        public string TarakoneshDate { get; set; }
        public string TarakoneshKind { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Price { get; set; }
    }
}
